// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenToWork.Models.Context;

#nullable disable

namespace OpenToWork.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904021619_AddMigrationInfoAndDocuments")]
    partial class AddMigrationInfoAndDocuments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenToWork.Models.Entities.ADAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "IsDeleted");

                    b.HasIndex("SCUserId", "IsDeleted");

                    b.HasIndex("EntityType", "EntityId", "IsDeleted");

                    b.ToTable("AD_AuditLogs", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ApplicationSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("AvailableFromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("ExpectedSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PT_VacancyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_CandidateId", "PT_VacancyId", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("PT_CandidateId", "Status", "IsDeleted");

                    b.HasIndex("PT_VacancyId", "Status", "IsDeleted");

                    b.ToTable("PT_Applications", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("Availability")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("HasPassport")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProfilePublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("WizardCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("WizardStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("WorkAuthorization")
                        .HasColumnType("int");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identification");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("WizardCompleted", "IsDeleted");

                    b.ToTable("PT_Candidates", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateCertification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CredentialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_CandidateId", "IsDeleted");

                    b.ToTable("PT_CandidateCertifications", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_CandidateId", "IsDeleted");

                    b.ToTable("PT_CandidateEducations", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurrentJob")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName", "IsDeleted");

                    b.HasIndex("PT_CandidateId", "IsDeleted");

                    b.ToTable("PT_CandidateExperiences", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateRecruitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentStage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PT_VacancyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("StageEnteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_VacancyId");

                    b.HasIndex("AssignedToUserId", "IsDeleted");

                    b.HasIndex("CurrentStage", "IsDeleted");

                    b.HasIndex("SCUserId", "IsDeleted");

                    b.HasIndex("SCUserId", "PT_VacancyId", "IsDeleted");

                    b.ToTable("PT_CandidateRecruitments", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateRecruitmentPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("AcceptedContractType")
                        .HasColumnType("int");

                    b.Property<int?>("AvailabilityToJoin")
                        .HasColumnType("int");

                    b.Property<string>("AvailableDays")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("AvailableHolidays")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AvailableSchedule")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("AvailableWeekends")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("ExpectedSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PT_CandidateRecruitmentId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("PreferredWorkShift")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_CandidateRecruitmentId")
                        .IsUnique();

                    b.HasIndex("IsCompleted", "IsDeleted");

                    b.HasIndex("PT_CandidateRecruitmentId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_CandidateRecruitmentPreferences", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PT_CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PT_SkillId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_SkillId", "IsDeleted");

                    b.HasIndex("PT_CandidateId", "PT_SkillId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_CandidateSkills", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("Name", "IsDeleted");

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_Companies", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTInvestigationChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCustom")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PT_CandidateRecruitmentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("IsCompleted", "IsDeleted");

                    b.HasIndex("PT_CandidateRecruitmentId", "Step", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_InvestigationChecklists", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTRecruitmentDismissal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DismissedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PT_CandidateRecruitmentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DismissedByUserId");

                    b.HasIndex("PT_CandidateRecruitmentId")
                        .IsUnique();

                    b.HasIndex("PT_CandidateRecruitmentId", "IsDeleted");

                    b.ToTable("PT_RecruitmentDismissals", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTRecruitmentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("PT_CandidateRecruitmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SY_DocumentTypeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SY_DocumentTypeId");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("PT_CandidateRecruitmentId", "IsDeleted");

                    b.HasIndex("Status", "IsDeleted");

                    b.HasIndex("PT_CandidateRecruitmentId", "SY_DocumentTypeId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_RecruitmentDocuments", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTRecruitmentStageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("FromStage")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PT_CandidateRecruitmentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ToStage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CreatedAt", "IsDeleted");

                    b.HasIndex("PT_CandidateRecruitmentId", "IsDeleted");

                    b.ToTable("PT_RecruitmentStageLogs", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTReferenceCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PT_InvestigationChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_InvestigationChecklistId", "IsDeleted");

                    b.ToTable("PT_ReferenceChecks", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "IsDeleted");

                    b.HasIndex("Name", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_Skills", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTTechnicalEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EvaluatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EvaluationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PT_CandidateRecruitmentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Recommendation")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedByUserId", "IsDeleted");

                    b.HasIndex("PT_CandidateRecruitmentId", "IsDeleted");

                    b.ToTable("PT_TechnicalEvaluations", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTTempVacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("EnglishLevel")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt", "IsDeleted");

                    b.HasIndex("IsPublished", "IsDeleted");

                    b.HasIndex("SCUserId", "IsDeleted");

                    b.ToTable("PT_TempVacancies", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("EnglishLevel")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PT_CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("ViewsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WorkMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("PT_CompanyId", "IsDeleted");

                    b.HasIndex("Status", "IsDeleted");

                    b.HasIndex("Category", "Status", "IsDeleted");

                    b.HasIndex("Location", "Status", "IsDeleted");

                    b.HasIndex("WorkMode", "Status", "IsDeleted");

                    b.ToTable("PT_Vacancies", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancySkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int?>("MinProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("PT_SkillId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PT_VacancyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PT_SkillId", "IsDeleted");

                    b.HasIndex("PT_VacancyId", "PT_SkillId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("PT_VacancySkills", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsRevoked", "IsDeleted");

                    b.ToTable("SC_RefreshTokens", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("GoogleId")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("PrimaryRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("GoogleId IS NOT NULL AND IsDeleted = 0");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.ToTable("SC_Users", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId", "IsTrusted");

                    b.HasIndex("SCUserId", "DeviceHash", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SC_UserDevices", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("SCUserId", "Role", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SC_UserRoles", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYDocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "IsDeleted");

                    b.HasIndex("Name", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SY_DocumentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("85b7ec75-18a3-40a1-a397-6eb9d097a0bb"),
                            Category = "Identidad",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7689),
                            Description = "Pasaporte válido y en vigor",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Pasaporte",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("927563cf-44a5-43fe-9fde-513ac20fde22"),
                            Category = "Identidad",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7701),
                            Description = "DNI / NIE / Cédula de identidad",
                            IsDeleted = false,
                            IsRequired = true,
                            Name = "Documento de identidad",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("4d8f87ad-bb64-46a7-9e8a-3ffd5e273319"),
                            Category = "Migratorio",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7707),
                            Description = "Autorización de trabajo en el país de destino",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Permiso de trabajo",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("0d3783fa-0667-4eea-9fbe-87e7946e9bd0"),
                            Category = "Habilitación",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7725),
                            Description = "Permiso de conducir válido",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Licencia de conducir",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("ac73637c-18b9-4956-91d2-b9fe847eee86"),
                            Category = "Migratorio",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7730),
                            Description = "Visado que habilita a trabajar legalmente",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Visado de trabajo",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("0e2bbc0d-0127-4b2c-9145-8b0aa4256dae"),
                            Category = "Salud",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7735),
                            Description = "Tarjeta sanitaria europea (TSE) o seguro médico privado",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Tarjeta sanitaria",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("3402ca6a-8da1-4e7a-be98-40c3b744ef54"),
                            Category = "Legal",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7755),
                            Description = "Certificado de antecedentes penales apostillado",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Certificado de antecedentes penales",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("0ea8a3d8-02a6-4224-bf31-e74f2adb30be"),
                            Category = "Formación",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7763),
                            Description = "Título habilitante o certificación profesional",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Titulo / Certificación profesional",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("bb942f7c-9b35-497a-aa79-82567793d345"),
                            Category = "Fiscal",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7768),
                            Description = "Documento con número de afiliación a la seguridad social",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Nº Seguridad Social",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("b773d6eb-37d1-4d8e-942f-cd2b11ede05e"),
                            Category = "Fiscal",
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(7772),
                            Description = "Justificante de cuenta bancaria a nombre del candidato",
                            IsDeleted = false,
                            IsRequired = false,
                            Name = "Cuenta bancaria (IBAN)",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYUserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("es");

                    b.Property<int?>("PreferredRole")
                        .HasColumnType("int");

                    b.Property<Guid>("SCUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("navy");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SCUserId")
                        .IsUnique();

                    b.HasIndex("SCUserId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("SY_UserPreferences", (string)null);
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYWizardStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("StepTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StepNumber", "IsDeleted")
                        .IsUnique();

                    b.HasIndex("Order", "Phase", "IsDeleted");

                    b.ToTable("SY_WizardSteps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("922edf5c-4182-4c01-a9b9-662566887d36"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8125),
                            Description = "Tell us about yourself",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 1,
                            Phase = 1,
                            StepName = "PersonalData",
                            StepNumber = 1,
                            StepTitle = "Personal Data"
                        },
                        new
                        {
                            Id = new Guid("d36faf65-ca5e-4ee3-96f1-0513749dbb61"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8136),
                            Description = "Where are you located?",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 2,
                            Phase = 1,
                            StepName = "Location",
                            StepNumber = 2,
                            StepTitle = "Location"
                        },
                        new
                        {
                            Id = new Guid("3e69a59c-251d-441c-91ce-c8786f73e188"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8141),
                            Description = "Your professional information",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 3,
                            Phase = 1,
                            StepName = "ProfessionalProfile",
                            StepNumber = 3,
                            StepTitle = "Professional Profile"
                        },
                        new
                        {
                            Id = new Guid("10a8f0e3-7d9f-4c34-80b6-4138695988f7"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8146),
                            Description = "Select your skills",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 4,
                            Phase = 1,
                            StepName = "Skills",
                            StepNumber = 4,
                            StepTitle = "Skills"
                        },
                        new
                        {
                            Id = new Guid("7cd7673d-c748-4f8e-950f-27c023529c2c"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8150),
                            Description = "Choose your preference",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 5,
                            Phase = 1,
                            StepName = "Preferences",
                            StepNumber = 5,
                            StepTitle = "What do you want to do?"
                        },
                        new
                        {
                            Id = new Guid("3df52b0a-e0f1-4fa5-a922-17fd80b4f2e4"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8158),
                            Description = "Verify your data is correct",
                            IsDeleted = false,
                            IsRequired = true,
                            Order = 6,
                            Phase = 1,
                            StepName = "Confirmation",
                            StepNumber = 6,
                            StepTitle = "Review and Confirm"
                        },
                        new
                        {
                            Id = new Guid("c6455f9d-0011-4021-b0ff-6cf8153dee8a"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8162),
                            Description = "Add your work experience",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 7,
                            Phase = 2,
                            StepName = "WorkExperience",
                            StepNumber = 7,
                            StepTitle = "Work Experience"
                        },
                        new
                        {
                            Id = new Guid("e610cd9d-28da-4b8c-a7e1-2209b9809e17"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8166),
                            Description = "Add your education",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 8,
                            Phase = 2,
                            StepName = "Education",
                            StepNumber = 8,
                            StepTitle = "Education"
                        },
                        new
                        {
                            Id = new Guid("9fc2c42a-fe0f-4070-9087-e40d6df4e5da"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8170),
                            Description = "Add your certifications",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 9,
                            Phase = 2,
                            StepName = "Certifications",
                            StepNumber = 9,
                            StepTitle = "Certifications"
                        },
                        new
                        {
                            Id = new Guid("1d6c9d3b-8cca-4c18-ad98-09dd90af2ef2"),
                            CreatedAt = new DateTime(2026, 9, 4, 2, 16, 17, 685, DateTimeKind.Utc).AddTicks(8177),
                            Description = "Upload your CV/resume",
                            IsDeleted = false,
                            IsRequired = false,
                            Order = 10,
                            Phase = 2,
                            StepName = "UploadCV",
                            StepNumber = 10,
                            StepTitle = "Upload CV"
                        });
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.ADAuditLog", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany()
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTApplication", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTVacancy", "Vacancy")
                        .WithMany("Applications")
                        .HasForeignKey("PT_VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("Candidate")
                        .HasForeignKey("OpenToWork.Models.Entities.PTCandidate", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateCertification", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("Certifications")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateEducation", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("Educations")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateExperience", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("Experiences")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateRecruitment", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("OpenToWork.Models.Entities.PTVacancy", "Vacancy")
                        .WithMany()
                        .HasForeignKey("PT_VacancyId");

                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany()
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("User");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateRecruitmentPreferences", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidateRecruitment", "Recruitment")
                        .WithOne("Preferences")
                        .HasForeignKey("OpenToWork.Models.Entities.PTCandidateRecruitmentPreferences", "PT_CandidateRecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateSkill", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("PT_CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTSkill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("PT_SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCompany", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("Company")
                        .HasForeignKey("OpenToWork.Models.Entities.PTCompany", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTInvestigationChecklist", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId");

                    b.HasOne("OpenToWork.Models.Entities.PTCandidateRecruitment", "Recruitment")
                        .WithMany("InvestigationChecklist")
                        .HasForeignKey("PT_CandidateRecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedByUser");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTRecruitmentDismissal", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "DismissedByUser")
                        .WithMany()
                        .HasForeignKey("DismissedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTCandidateRecruitment", "Recruitment")
                        .WithOne("Dismissal")
                        .HasForeignKey("OpenToWork.Models.Entities.PTRecruitmentDismissal", "PT_CandidateRecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DismissedByUser");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTRecruitmentDocument", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCandidateRecruitment", "Recruitment")
                        .WithMany("RecruitmentDocuments")
                        .HasForeignKey("PT_CandidateRecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.SYDocumentType", "DocumentType")
                        .WithMany("RecruitmentDocuments")
                        .HasForeignKey("SY_DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.SCUser", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId");

                    b.Navigation("DocumentType");

                    b.Navigation("Recruitment");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTRecruitmentStageLog", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTCandidateRecruitment", "Recruitment")
                        .WithMany("StageLogs")
                        .HasForeignKey("PT_CandidateRecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTReferenceCheck", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTInvestigationChecklist", "Checklist")
                        .WithMany("ReferenceChecks")
                        .HasForeignKey("PT_InvestigationChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTTechnicalEvaluation", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "EvaluatedByUser")
                        .WithMany()
                        .HasForeignKey("EvaluatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTCandidateRecruitment", "CandidateRecruitment")
                        .WithMany("TechnicalEvaluations")
                        .HasForeignKey("PT_CandidateRecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateRecruitment");

                    b.Navigation("EvaluatedByUser");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTTempVacancy", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("TempVacancies")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancy", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTCompany", "Company")
                        .WithMany("Vacancies")
                        .HasForeignKey("PT_CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancySkill", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.PTSkill", "Skill")
                        .WithMany()
                        .HasForeignKey("PT_SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenToWork.Models.Entities.PTVacancy", "Vacancy")
                        .WithMany("VacancySkills")
                        .HasForeignKey("PT_VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCRefreshToken", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserDevice", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUserRole", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYUserPreference", b =>
                {
                    b.HasOne("OpenToWork.Models.Entities.SCUser", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("OpenToWork.Models.Entities.SYUserPreference", "SCUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidate", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CandidateSkills");

                    b.Navigation("Certifications");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCandidateRecruitment", b =>
                {
                    b.Navigation("Dismissal");

                    b.Navigation("InvestigationChecklist");

                    b.Navigation("Preferences");

                    b.Navigation("RecruitmentDocuments");

                    b.Navigation("StageLogs");

                    b.Navigation("TechnicalEvaluations");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTCompany", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTInvestigationChecklist", b =>
                {
                    b.Navigation("ReferenceChecks");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTSkill", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.PTVacancy", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("VacancySkills");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SCUser", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("Company");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TempVacancies");

                    b.Navigation("UserDevices");

                    b.Navigation("UserPreference");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OpenToWork.Models.Entities.SYDocumentType", b =>
                {
                    b.Navigation("RecruitmentDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
